---
- name: wait for all mgr to be up
  command: "{{ hostvars[groups[mon_group_name][0]]['container_exec_cmd'] | default('') }} ceph --cluster {{ cluster }} mgr dump -f json"
  register: mgr_dump
  retries: 30
  delay: 5
  delegate_to: "{{ groups[mon_group_name][0] }}"
  changed_when: false
  until:
    - mgr_dump.rc == 0
    - (mgr_dump.stdout | from_json).available | bool
  when: not ansible_check_mode

- name: add modules to ceph-mgr
  ceph_mgr_module:
    name: "{{ ceph_mgr_modules }}"
    cluster: "{{ cluster }}"
    state: auto
  environment:
    CEPH_CONTAINER_IMAGE: "{{ ceph_docker_registry + '/' + ceph_docker_image + ':' + ceph_docker_image_tag if containerized_deployment | bool else None }}"
    CEPH_CONTAINER_BINARY: "{{ container_binary }}"
  delegate_to: "{{ groups[mon_group_name][0] }}"
